language: java

jdk:
  - openjdk8
  - openjdk11

deploy:
  provider: releases
  token: "GITHUB_API_KEY"
  file: "build/libs/*.jar"
  edge: true
  on:
    branch: master
    tags: true
    jdk: openjdk11
